version: '3'

services:
  nginx:
    image: 'nginx:1.15.12-alpine'
    ports:
      - '8083:80'
    volumes:
      - ./fixtures/nginx_fast_slow.conf:/etc/nginx/conf.d/default.conf:ro
      - ./fixtures/data:/usr/share/nginx/html:ro
